# KIND cluster configuration with port mapping
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31000  # Maps to NodePort 31000
        hostPort: 31000
        protocol: TCP
  - role: worker
  - role: worker